apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: bi-dataservice-hpa
  namespace: designeronly
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bi-dataservice-deployment
  minReplicas: 3
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 60
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
