apiVersion: v1
kind: Service
metadata:
  name: bi-dataservice-service
  namespace: designerservice  
  labels:
    app: bi-dataservice
spec:
  type: NodePort
  ports:
  - name: bi-dataservice-port
    port: 6007
    targetPort: 80
    protocol: TCP
  selector:
    app: bi-dataservice
