apiVersion: apps/v1
kind: Deployment
metadata:
  name: internal-web-deployment
  namespace: boldbi-cloud-test
spec:
  selector:
    matchLabels:
      app: internal-web
  # replicas: 1
  template:
    metadata:
      labels:
        app: internal-web
    spec:
      containers:
      - name: internal-web-container
        image: us-docker.pkg.dev/boldbi-dev-296107/boldbik8s/boldbi-internal-service-cloud:5.2.48
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
            memory: 750M
          limits:
            cpu: 250m
            memory: 750M
        envFrom:
        - secretRef:
              name: boldid-web-secret
